---
abstract: 'Distributed semaphores via Apache ZooKeeper'
author:
  - 'Yandex LLC'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ZooKeeper-Semaphore
requires:
  Carp: 0
  Net::ZooKeeper: 0
  Net::ZooKeeper::Lock: 0
  Params::Validate: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/komarov/Net-ZooKeeper-Semaphore
  repository: git://github.com/komarov/Net-ZooKeeper-Semaphore.git
version: 0.01
